apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  creationTimestamp: "2024-06-01T11:36:23Z"
  generation: 4813
  name: cluster
  resourceVersion: "7715406"
  uid: 48da6356-4613-4af7-b7c9-5dcb1dcd95ae
spec:
  clusterNetwork:
  - cidr: 10.52.0.0/14
    hostPrefix: 23
  defaultNetwork:
    ovnKubernetesConfig:
      egressIPConfig: {}
      gatewayConfig:
        ipv4: {}
        ipv6: {}
        routingViaHost: false
      genevePort: 6081
      hybridOverlayConfig:
        hybridClusterNetwork:
        - cidr: 10.56.0.0/14
          hostPrefix: 23
        hybridOverlayVXLANPort: 4789
      ipsecConfig:
        mode: Disabled
      mtu: 1400
      policyAuditConfig:
        destination: "null"
        maxFileSize: 50
        maxLogFiles: 5
        rateLimit: 20
        syslogFacility: local0
    type: OVNKubernetes
  deployKubeProxy: false
  disableMultiNetwork: false
  disableNetworkDiagnostics: false
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  serviceNetwork:
  - 10.61.0.0/16
  unsupportedConfigOverrides: null
  useMultiNetworkPolicy: false
status:
  conditions:
  - lastTransitionTime: "2024-06-01T11:36:23Z"
    status: "False"
    type: ManagementStateDegraded
  - lastTransitionTime: "2024-06-11T09:55:58Z"
    message: DaemonSet "/openshift-ovn-kubernetes/ovnkube-node" rollout is not making
      progress - pod ovnkube-node-4ghhl is in CrashLoopBackOff State
    reason: RolloutHung
    status: "True"
    type: Degraded
  - lastTransitionTime: "2024-06-01T11:36:23Z"
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2024-06-11T06:41:42Z"
    message: DaemonSet "/openshift-ovn-kubernetes/ovnkube-node" is not available (awaiting
      2 nodes)
    reason: Deploying
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-06-01T11:44:29Z"
    status: "True"
    type: Available
  readyReplicas: 0
  version: 4.15.13
